= {lab_name}

Welcome to the Red Hat OpenStack Services on OpenShift (RHOSO) lab instructions.
These instructions will guide you through the installation of the next generation of Red Hat's OpenStack product onto an existing OpenShift Cluster utilizing a bastion host and a single host for the data plane.

In this lab, you will use the following infrastructure:

* A 3 OCP controller + 3 OCP workers nodes 4.15 OCP cluster
* A bastion host to access to the OCP environment
* A RHEL 9.4 virtualised compute host

In this lab, you will cover the following topics:

* xref:openshift-walkthrough.adoc[Navigate the OpenShift installation]
* xref:openstack-operators.adoc[Navigate the OpenStack Operators]
* xref:network-isolation.adoc[Navigate the network isolation configuration]
* xref:control-plane.adoc[Navigate the Control Plane]
* xref:data-plane.adoc[Navigate the Data plane]
* xref:access.adoc[Access OpenStack]

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

*Be sure to review all commands carefully both for functionality and syntax!*
